### ISSUE TITLE
Elements in service geographic extent need boxing up and correctly labelling

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#12] opened 2019-07-09 16:08 UTC
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1063-gemini-services#15

![Screenshot from 2019-07-09 17-08-01](https://user-images.githubusercontent.com/1544849/60905043-2b694e00-a26c-11e9-920f-047f25eec34f.png)

**Comment by archaeogeek** [comment] 2019-07-18 16:04
Now boxed, but seeing odd behaviour with more than 2 extent codes- not all of them have the arrows to move them around, see 
![Screenshot from 2019-07-17 17-38-44](https://user-images.githubusercontent.com/1544849/61473304-0f596100-a97e-11e9-8a98-e0a66c02b820.png)

**Comment by josegar74** [comment] 2019-08-19 08:01
@archaeogeek Are you using the `services` branch? I see commits there, but using it and adding a geographic identifier I don't get that section in the metadata editor even if I see the following code to display the element:

https://github.com/AstunTechnology/iso19139.gemini23/blob/services/src/main/plugin/iso19139.gemini23/layout/config-editor.xml#L3396-L3399

I have added the following snippet from the GEMINI 2.3 guidelines:

```
               <gmd:geographicElement>
                  <gmd:EX_GeographicDescription>
                     <gmd:geographicIdentifier>
                        <gmd:MD_Identifier>
                           <gmd:authority>
                              <gmd:CI_Citation>
                                 <gmd:title>
                                    <gco:CharacterString>ISO 3166-2</gco:CharacterString>
                                 </gmd:title>
                                 <gmd:date>
                                    <gmd:CI_Date>
                                       <gmd:date>
                                          <gco:Date>1998</gco:Date>
                                       </gmd:date>
                                       <gmd:dateType>
                                          <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                               codeListValue="revision"/>
                                       </gmd:dateType>
                                    </gmd:CI_Date>
                                 </gmd:date>
                              </gmd:CI_Citation>
                           </gmd:authority>
                           <gmd:code>
                              <gco:CharacterString>GB-ENG</gco:CharacterString>
                           </gmd:code>
                        </gmd:MD_Identifier>
                     </gmd:geographicIdentifier>
                  </gmd:EX_GeographicDescription>
               </gmd:geographicElement>
```

Can you check if maybe something is not committed or confirm the branch to use?

**Comment by archaeogeek** [comment] 2019-08-19 08:19
Hi Jose,

I do have some very minor changes in config-editor.xml (I added srv:serviceType in fieldswithfieldset) and in codelists.xml, but those are the only changes, and yes I am using the services branch. I've attached the example services file I'm using for testing (zipped so that GitHub supports it). If that file doesn't display the extent code for you then I will back out my changes and see if that makes any difference.

Jo

[3ff4ed80-df83-45f9-bf43-e30c50b4dc44.zip](https://github.com/AstunTechnology/iso19139.gemini23/files/3514821/3ff4ed80-df83-45f9-bf43-e30c50b4dc44.zip)

**Comment by josegar74** [comment] 2019-08-23 05:55
I get the sections as you, probably the metadata I was using didn't have the proper elements. 

I see 4 sections, but are repeated as there's only 2 `gmd:geographicIdentifier` elements. Checking the reason for this.

**Comment by josegar74** [comment] 2019-08-23 06:09
The problem is with these 4 elements: https://github.com/AstunTechnology/iso19139.gemini23/blob/services/src/main/plugin/iso19139.gemini23/layout/config-editor.xml#L3396-L3414


```
<field
    xpath="/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicDescription"
    if="count(gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification) > 0">
</field>

<field
    xpath="/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicDescription"
    if="count(gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification) > 0">
</field>

<field
    xpath="/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement"
    if="count(gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification) > 0">
</field>

<field
    xpath="/gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification/srv:extent/gmd:EX_Extent/gmd:geographicElement"
    if="count(gmd:MD_Metadata/gmd:identificationInfo/srv:SV_ServiceIdentification) > 0">
</field>
```

The first 2 use this xpath: `.../gmd:geographicElement/gmd:EX_GeographicDescription` while the 2  last use `.../gmd:geographicElement` that includes the previous one also.

I have commented the first 2, but before committing want to confirm with you the reason of the 4 blocks?

![extent-services](https://user-images.githubusercontent.com/1695003/63570403-5938f680-c57d-11e9-890d-d13fa12aa463.png)

**Comment by archaeogeek** [comment] 2019-09-02 16:01
Hi Jose,

I think my commit referenced here fixes the issue- the first blocks are for the extent as an extent code, and the second are for the bounding box. However, in applying this, I have realised also that the inflate-metadata process needs revising to take into account services. I'll add a separate issue for that, but would appreciate if you could test this commit for me and close if you think I've fixed it?

Thanks

Jo

**Comment by josegar74** [comment] 2019-09-03 08:13
Now doesn't display duplicated elements, but the xpath in the field `/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicDescription`  causes that there're no arrows to move elements (to display the arrows should be used the xpah `/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement`.

I think that is not a problem, please confirm and if so, the issue can be closed.

**Closed** 2019-09-03 10:48 UTC
