### ISSUE TITLE
Thesaurus identifier anchor / thesaurus.download service

### ISSUE THREAD

**Issue by PeterParslow** [AstunTechnology/iso19139.gemini23#148] opened 2024-08-14 13:39 UTC
**Describe the bug**
In it's Keywords section each ISO 19139 XML record encodes each thesaurus with an identifier using gmx:Anchor, but the Anchor URL (href) doesn't work.

**To Reproduce**

1. Select a record
2. Download as XML
3. Scroll down to gmd:descriptiveKeywords/gmd:MD_Keyword/gmd:thesaurusName/gmd:CI_Citation/gmd:identifier/gmd:MD_Identifier/gmd:code/gmx:Anchor
4. Copy the xlink:href target
5.  Paste it into a browser

You most likely get

{"error": { "message": "Service not found" , "class": "ServiceNotFoundEx" , "request": {} } }

**Expected behavior**
The thesaurus should be opened, either at its original location (preferable for external thesauri) or by enabling the "thesaurus.download" service

**Screenshots**

**Additional context**
Specifically occurs on Geonetwork 4.2 as run by Astun for Ordnance Survey (https://osmetadata.astuntechnology.com/geonetwork/srv/eng) but I can't see that it is an OS customisation or even an Astun/GEMINI customisation. Admittedly, I haven't found my way around the Geonetwork code to see where the XML is generated (presumably, the 19139 plugin?)

**Comment by archaeogeek** [comment] 2024-08-14 13:46
@PeterParslow what is the URL for the xlink:href?

**Comment by PeterParslow** [comment] 2024-08-14 14:25
Here's are three examples: 

- https://osmetadata.astuntechnology.com/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeutheme-theme
- https://osmetadata.astuntechnology.com/geonetwork/srv/eng/thesaurus.download?ref=external.theme.gemet
- https://osmetadata.astuntechnology.com/geonetwork/srv/eng/thesaurus.download?ref=external.theme.NGD-theme-feature-hierarchy

Note: the really useful URL generally appears as the Anchor for each Keyword and sometimes (for the whole thesaurus) as the Anchor for the title of the thesaurus. Where that's the case, this URL/Anchor for the identifier of the thesaurus seems to me to be redundant (as well as not working) - so if I/we could get the "title Anchor" to always appear, then this issue wouldn't matter to me.

In our set up, 

1. the GEMET - INSPIRE themes thesaurus gets a useful Anchor for its title & this non-working one for the identifier.
2. the GEMET - Concepts thesaurus doesn't get a useful Anchor for its title, so I tried the 'id' one
3. the INSPIRE feature concept dictionary thesaurus gets a useful Anchor for its title and the same useful Anchor (https://inspire.ec.europa.eu/featureconcept) for its identifier
4. our own NGD thesaurus gets a correct but non-working Anchor for its title (http://os.uk/vocabularies/ngd) and this non working one for id: https://osmetadata.astuntechnology.com/geonetwork/srv/eng/thesaurus.download?ref=external.theme.NGD-theme-feature-hierarchy

The fact that one of them uses the 'direct' external URL suggests its set somewhere in the thesaurus metadata, with (presumably) the 'thesaurus.download' URL as some sort of default - assembled from the RDF filename? I can't see anything in the Administration interface that seems to influence the URLs (other than perhaps the RDF filename in 1,2 & 4 above)

**Comment by archaeogeek** [comment] 2024-08-15 16:33
Since I no longer have admin access to osmetadata.astuntechnology.com, this is from memory... 

The Anchor URL is formed from the thesaurus- it's of the form {thesaurus_type}.{thesaurus_discipline}.{thesaurus_file_name} where type is either local or external, and the discipline is chosen when you create or add the thesaurus. See https://docs.geonetwork-opensource.org/4.2/administrator-guide/managing-classification-systems/managing-thesaurus/#creating-or-importing-a-thesaurus noting that they use the term type for both external/local and the discipline.

The URL part before the query-string is created from the Catalogue URL in the admin settings.

So... if the URL that ends up in the metadata is wrong, it may well be because the thesaurus now has a different filename, and perhaps that it's local when it was previously external. Once you've identified the issue, you will potentially need to re-upload the thesaurus with the correct filename, or update the metadata records to use the new URL. 

In any case it's not a Gemini issue as it's all handled outside of the metadata schema- so I'd suggest either a support ticket, or an issue in https://github.com/AstunTechnology/os-custom-geonetwork (but not assigned to me in that case!)

**Comment by archaeogeek** [comment] 2024-08-16 09:43
@PeterParslow or @alexarobu I'll close this so you can create a support ticket or issue in https://github.com/AstunTechnology/os-custom-geonetwork as appropriate

**Comment by PeterParslow** [comment] 2024-08-20 15:05
Further comments here, which I'll then reference from one (or both!) of the above:

I don't see 1 & 2 as OS specific, although I can't find it in Core GeoNetwork or . The name part of the Anchor URL matches the names to be seen here: https://github.com/AstunTechnology/os-custom-geonetwork/tree/os-4.2.x/thesauri/external/thesauri/theme, but the URL doesn't work (I wonder if that's because they are in a 'theme' folder within the external/thesauri folder, even though that is as per the instructions at https://github.com/AstunTechnology/os-custom-geonetwork/wiki/Configuring-and-customising-the-portal). At https://github.com/geonetwork/util-gemet/tree/master/thesauri, gemet.rdf isn't in a "theme" sub-folder.

It seems that 3 is handled as a special case somewhere (again, not OS specific) in that it gets a direct title Anchor & id Anchor to the _external_ URL, not the 'download' one - so it's not really handled like a GeoNetwork thesaurus at all.

Only number 4 is OS specific, and Jo's explanation doesn't seem to quite work there: the file name in GitHub has a date stamp part but the "file name" used to create the URL doesn't.

I'll raise it as an OS ticket, although I suspect the problem is not really in the OS specific config.

**Comment by alexarobu** [comment] 2024-10-02 11:23
@archaeogeek I had a look at this and I don't think all of it is OS-specific. 

Indeed the `gmx:Anchor` in the `gmd:title` element comes from the thesauri and so the broken OS NGD links are something that needs to be fixed by OS (@PeterParslow is aware)
```
<gmd:title>
      <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
</gmd:title>
```

But the second `gmx:anchor` element Peter referred to is not really OS-specific, for example:
```
<gmd:code>
  <gmx:Anchor xlink:href="https://osmetadata.astuntechnology.com/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeutheme-theme">geonetwork.thesaurus.external.theme.httpinspireeceuropaeutheme-theme</gmx:Anchor>
</gmd:code>
```

You are right, it is formed as you suggest, but the problem is the `/eng/thesaurus.download?ref=` bit in the `xlink:href=` attribute. 

For the link to actually resolve it would need changing to something like `/api/registries/vocabularies/` (e.g. https://osmetadata.astuntechnology.com/geonetwork/srv/api/registries/vocabularies/external.theme.httpinspireeceuropaeutheme-theme) to call the GeoNetwork endpoint that triggers the thesaurus download. 

I think we can easily fix this with an XSL transformation in https://github.com/AstunTechnology/iso19139.gemini23/blob/4.2.x/src/main/plugin/iso19139.gemini23/update-fixed-info.xsl or even just in the XML view file if we want to leave the original metadata unchanged (https://github.com/AstunTechnology/iso19139.gemini23/blob/4.2.x/src/main/plugin/iso19139.gemini23/formatter/xsl-view/view.xsl)

What are your thoughts? I can add the transformation if you think it's a good idea.

**Comment by archaeogeek** [comment] 2024-10-02 13:24
Still not a Gemini issue! Do a search for `thesaurus.download` in the core geonetwork repository- it seems as if should be using the api version of the URL. Maybe check other installs to see if they have the same problem? Also check new records vs older ones- does it happen in both?

**Closed as completed** 2024-10-02 13:39 UTC
